### ISSUE TITLE
HACS integration won't update automatically?

### ISSUE THREAD

**Issue by mr-leo** [dingo35/ha-SmartEVSEv3#24]
I discovered (in manifest.json) that i still use version 1.0.10. HACS never mentions updates on the smartevse-3 integration. It does on other custom integrations. I thought that "the main advantage of this installation method (HACS) is that HomeAssistant will inform you of updates". What am i doing wrong here? Can i just overwrite the files of the newer version?

**Comment by dingo35** [comment]
First of all, thanks for your donation, you are my first sponsor :-).

Now you have a good question.... do your other HACS installed integrations update automatically? 

I get a notification in HA that new updates are available:
![Screenshot_20240122_065643_Home Assistant](https://github.com/dingo35/ha-SmartEVSEv3/assets/6104159/c20f227f-082a-49cc-8b03-770a7647f637)

Now I must say that its been a long time since I brought out a new release. I am on the verge of bringing out a new release because of some deprecated variables in HA, I am happy to wait until you are ready to test, but mind you, I can only do this once...

**Comment by dingo35** [comment]
You can just overwrite the files in the custom_components directory, but I would try to get it installed correctly through HACS because of future updates....

**Comment by mr-leo** [comment]
I get my HACS updates exactly the same way, except never from the smartevse-3 intergration. I will do it manually.

**Comment by dingo35** [comment]
Ok mr leo just released v1.1.1 and it showed up in my notifications; does it work for you now?

**Comment by mr-leo** [comment]
Nope! (HACS 1.34.0)

**Comment by dingo35** [comment]
How about if you goto:
HACS and press the smartevse component?

My andoid app gives this info:

![Screenshot_20240123_140514_Home Assistant](https://github.com/dingo35/ha-SmartEVSEv3/assets/6104159/2dbf5ebc-b07c-4d71-977e-81a7f4ea16e6)

Perhaps "Update Information" does anything?

**Comment by mr-leo** [comment]
That helped me in the right direction! "Update information" does nothing but "Opnieuw downloaden" (download again) fixes the problem! I am curious if future updates will go automatically.  Thx!

![IMG_3862](https://github.com/dingo35/ha-SmartEVSEv3/assets/34186575/46a9f1f5-6ca2-43ec-89c4-450f7a018920)
![IMG_3861](https://github.com/dingo35/ha-SmartEVSEv3/assets/34186575/3b99b8cb-5291-4252-8b7d-46552ac4ae8a)
![Screenshot_1](https://github.com/dingo35/ha-SmartEVSEv3/assets/34186575/dba4c111-6ee7-4102-bb40-2a5c77245f13)
